services:
  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_DB: squid
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - "${DB_PORT}:5432"
      # command: ["postgres", "-c", "log_statement=all"]
    shm_size: 1gb


  subsquid:
    build: .
    container_name: subsquid
    command: ["sh", "-c", "sqd run"]
    environment:
      - DB_HOST=db
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - RPC_ETH_HTTP=${RPC_ETH_HTTP}
      - CONTRACT_ADDRESS=${CONTRACT_ADDRESS}
      - STARTING_BLOCK=${STARTING_BLOCK}
      - GATEWAY=${GATEWAY}
      - NETWORK=${NETWORK}
      - VERSION=${VERSION}
    ports:
      - "4350:4350"
    depends_on:
      - db